version: '3'
services:
  web:
    #platform: linux/amd64
    container_name: "web"
    build: .
    ports:
      - "3000:3000"
      - "8000:8000"
  #  depends_on:
  #    - db

  #db:
  #  image: postgres:14.1-alpine
  #  restart: always
  #  environment:
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=postgres
  #  ports:
  #    - '5432:5432'
  #  volumes:
  #    - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local